import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { prepareMarketSnapshots, requestMarketSeries } from "../../supabase/functions/generate-premarket-plan/marketSnapshot.ts";

const candle = (timestamp = "2026-08-14", close = 100) => ({ timestamp, open: close - 1, high: close + 2, low: close - 2, close, volume: 1000 });
function result(ticker, interval, status = "available") { return { candles: status === "available" ? [candle(), candle("2026-08-15", 101)] : [], diagnostic: { ticker, interval, status, httpStatus: status === "rate_limited" ? 429 : 200, providerCode: status === "rate_limited" ? 429 : null, providerMessage: null, durationMs: 1 } }; }
function requester(statuses = {}, calls = []) { return async (ticker, interval, outputsize) => { calls.push(`${ticker}:${interval}:${outputsize}`); return result(ticker, interval, statuses[`${ticker}:${interval}`] || statuses[interval] || "available"); }; }

describe("daily-first market preparation", () => {
  it("keeps daily + failed weekly as Partial and available", async () => { const output = await prepareMarketSnapshots(["NVDA"], "2026-08-17", "key", requester({ "1week": "unavailable" })); expect(output.marketData[0]).toMatchObject({ dataAvailability: "Partial", dataAvailable: true, weeklyTrend: "Unavailable" }); });
  it("requests only 65 daily candles and retains daily structure", async () => { const calls = []; const output = await prepareMarketSnapshots(["NVDA"], "2026-08-17", "key", requester({}, calls)); expect(output.marketData[0].dataAvailable).toBe(true); expect(calls).toEqual(["NVDA:1day:65"]); expect(output.marketData[0]).not.toHaveProperty("intradayTrend"); });
  it("keeps daily when every optional interval fails", async () => { const output = await prepareMarketSnapshots(["NVDA"], "2026-08-17", "key", requester({ "1week": "unavailable", "5min": "unavailable" })); expect(output.marketData[0]).toMatchObject({ dataAvailability: "Partial", dataAvailable: true }); });
  it("classifies a daily failure as Unavailable", async () => { const output = await prepareMarketSnapshots(["NVDA"], "2026-08-17", "key", requester({ "1day": "unavailable" })); expect(output.marketData[0]).toMatchObject({ dataAvailability: "Unavailable", dataAvailable: false }); });
  it("requests daily for every symbol without enrichment", async () => { const calls = []; await prepareMarketSnapshots(["QQQ", "SPY", "NVDA", "AMD"], "2026-08-17", "key", requester({}, calls)); expect(calls).toEqual(["QQQ:1day:65", "SPY:1day:65", "NVDA:1day:65", "AMD:1day:65"]); });
  it("preserves every daily snapshot without optional provider calls", async () => { const calls = []; const output = await prepareMarketSnapshots(["QQQ", "SPY", "NVDA"], "2026-08-17", "key", requester({}, calls)); expect(output.marketData.every((item) => item.dataAvailable)).toBe(true); expect(calls).toEqual(["QQQ:1day:65", "SPY:1day:65", "NVDA:1day:65"]); expect(output.diagnostics.find((item) => item.ticker === "NVDA" && item.interval === "1week")?.status).toBe("not_requested"); });
  it("allows QQQ and SPY with daily data but no intraday data", async () => { const output = await prepareMarketSnapshots(["QQQ", "SPY"], "2026-08-17", "key", requester({ "5min": "unavailable" })); expect(output.marketData.map((item) => [item.ticker, item.dataAvailable])).toEqual([["QQQ", true], ["SPY", true]]); });
  it("does not let one unavailable stock discard other symbols", async () => { const output = await prepareMarketSnapshots(["QQQ", "SPY", "NVDA", "AMD"], "2026-08-17", "key", requester({ "NVDA:1day": "unavailable" })); expect(output.marketData.find((item) => item.ticker === "NVDA")?.dataAvailable).toBe(false); expect(output.marketData.filter((item) => item.ticker !== "NVDA").every((item) => item.dataAvailable)).toBe(true); });
  it("does not request 1-minute data in active preparation", async () => { const calls = []; const output = await prepareMarketSnapshots(["QQQ"], "2026-08-17", "key", requester({}, calls)); expect(calls.some((call) => call.endsWith(":1min"))).toBe(false); expect(output.diagnostics.find((item) => item.interval === "1min")?.status).toBe("not_requested"); });
  it("contains no OpenAI call in the active preparation function", () => { const source = readFileSync(new URL("../../supabase/functions/prepare-premarket-data/index.ts", import.meta.url), "utf8"); expect(source).not.toMatch(/api\.openai\.com|OPENAI_API_KEY|\/v1\/responses/); });
  it("captures provider rate-limit diagnostics without exposing the request URL", async () => { const fetchImpl = async () => new Response(JSON.stringify({ status: "error", code: 429, message: "API credits exhausted" }), { status: 429, headers: { "Content-Type": "application/json" } }); const output = await requestMarketSeries("NVDA", "1week", 20, "secret", fetchImpl); expect(output.diagnostic).toMatchObject({ ticker: "NVDA", interval: "1week", status: "rate_limited", httpStatus: 429, providerCode: 429, providerMessage: "API credits exhausted" }); expect(JSON.stringify(output.diagnostic)).not.toContain("secret"); });
});
