import { useEffect,useMemo,useState } from "react";
import Button from "../ui/Button";
import { createReviewTag,fetchReviewTags } from "../../lib/reviewTagService";
import { gradeTradeReview,isQuickReviewComplete,SEQUENCE_STAGES } from "../../lib/tradeGrading";
import { buildQuickReviewPayload,createQuickReviewDraft } from "../../lib/workflow/quickReview";
const HELP={break:"Price decisively clears the planned/key level.",displacement:"Expansion shows real intent away from the level.",acceptance:"Price establishes beyond the level instead of immediately rejecting.",retest:"Price returns toward the setup area.",hold:"Structure stays valid on the retest.",trigger:"Entry confirmation occurred after the sequence."};
const VIOLATIONS=["None","Anticipated Entry","Chased","FOMO","Early Entry","No Confirmation","Oversized","Moved Stop Wider","Revenge Trade","Unplanned Trade","Overtraded","Broke Max Trades Rule","Entered Against Market Context","Poor R:R","Other"];
export function CompactPlanSummary({trade}){const side=String(trade.direction||"").toLowerCase();return <div className="planned-context"><p><strong>Preferred:</strong> {String(trade.planned_direction||"Unknown").toUpperCase()} · <strong>Actual:</strong> {String(trade.direction||"Unknown").toUpperCase()}</p><p>Scenario Match: {trade.planned_scenario_matched==null?"Unknown":trade.planned_scenario_matched?"Yes":"No"} · Preferred Direction Match: {(trade.preferred_direction_matched??trade.direction_matched)==null?"Unknown":(trade.preferred_direction_matched??trade.direction_matched)?"Yes":"No"}</p>{trade[`planned_${side}_scenario_enabled`]?<p><strong>{side.toUpperCase()} PLAN</strong> {[trade[`planned_${side}_trigger`],trade[`planned_${side}_setup`],trade[`planned_${side}_target`]].filter(Boolean).join(" · ")}</p>:null}</div>}
function Segments({label,value,options,onChange,help}){return <fieldset className="review-segments"><legend>{label}{help?<span title={help} aria-label={`${label}: ${help}`}> ?</span>:null}</legend><div>{options.map(([key,text])=><button type="button" key={key} aria-pressed={value===key} className={value===key?`selected ${key}`:""} onClick={()=>onChange(key)}>{text}</button>)}</div></fieldset>}
function TagPicker({label,kind,tags,selected,onChange,onCreated,required}){const[q,setQ]=useState("");const create=async()=>{const tag=await createReviewTag(kind,q);onCreated(tag);onChange([...new Set([...selected,tag.id])]);setQ("")};return <fieldset className="review-tag-picker"><legend>{label}{required?" *":""}</legend><div className="review-tag-search"><input aria-label={`Search or create ${label}`} value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search or create ${label.toLowerCase()}`}/><Button variant="secondary" disabled={!q.trim()} onClick={create}>+ Create</Button></div><div className="review-tag-options">{tags.filter(t=>t.name.toLowerCase().includes(q.toLowerCase())).map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>onChange(selected.includes(t.id)?selected.filter(id=>id!==t.id):[...selected,t.id])}/>{t.name}</label>)}</div></fieldset>}
export default function QuickReviewForm({trade,onSave,onSaveNext,onDetailedReview,isSaving}){const[draft,setDraft]=useState(()=>createQuickReviewDraft(trade));const[tags,setTags]=useState({setup:[],confluence:[]});const[message,setMessage]=useState("");useEffect(()=>{Promise.all([fetchReviewTags("setup"),fetchReviewTags("confluence")]).then(([setup,confluence])=>setTags({setup,confluence})).catch(e=>setMessage(e.message))},[]);const outcome=Number(trade.pnl||0)>0?"win":Number(trade.pnl||0)<0?"loss":"breakeven";const grade=useMemo(()=>gradeTradeReview(draft,outcome),[draft,outcome]);const update=(field,value)=>setDraft(d=>({...d,[field]:value}));const save=async(next=false)=>{setMessage("");try{await(next?onSaveNext:onSave)(buildQuickReviewPayload(draft,trade,tags));setMessage(isQuickReviewComplete(draft)?"Review saved.":"Review saved as In Progress.")}catch(e){setMessage(e.message||"Review could not be saved.")}};const toggle=v=>update("ruleViolations",v==="None"?(draft.ruleViolations.includes(v)?[]:[v]):(draft.ruleViolations.includes(v)?draft.ruleViolations.filter(x=>x!==v):[...draft.ruleViolations.filter(x=>x!=="None"),v]));return <form className="quick-review" onSubmit={e=>{e.preventDefault();save()}}><header className="quick-review-title"><div><p className="eyebrow">30–60 second workflow</p><h3>Quick Review</h3></div><strong>{isQuickReviewComplete(draft)?"Ready to save":"In Progress"}</strong></header>
<TagPicker label="Setup Type" kind="setup" tags={tags.setup} selected={draft.setupTagIds} onChange={v=>update("setupTagIds",v)} onCreated={tag=>setTags(t=>({...t,setup:[...t.setup.filter(x=>x.id!==tag.id),tag]}))} required/><TagPicker label="Confluences" kind="confluence" tags={tags.confluence} selected={draft.confluenceTagIds} onChange={v=>update("confluenceTagIds",v)} onCreated={tag=>setTags(t=>({...t,confluence:[...t.confluence.filter(x=>x.id!==tag.id),tag]}))}/>
<section><h4>Setup Sequence</h4><div className="sequence-grid">{SEQUENCE_STAGES.map(stage=><Segments key={stage} label={stage[0].toUpperCase()+stage.slice(1)} help={HELP[stage]} value={draft.sequence[stage]} options={[["met","✓ Met"],["not_met","✕ Not Met"],["na","— N/A"]]} onChange={v=>update("sequence",{...draft.sequence,[stage]:v})}/>)}</div></section>
<section><h4>Context</h4><div className="review-check-grid"><Segments label="Market / QQQ-SPY" value={draft.marketContext} options={[["aligned","Aligned"],["neutral","Neutral"],["against","Against"]]} onChange={v=>update("marketContext",v)}/><Segments label="Room / R:R" value={draft.roomQuality} options={[["good","Good"],["marginal","Marginal"],["poor","Poor"]]} onChange={v=>update("roomQuality",v)}/><Segments label="Planned Key Level" value={draft.plannedLevel} options={[["yes","Yes"],["no","No"]]} onChange={v=>update("plannedLevel",v)}/></div></section>
<section><h4>Execution / Risk</h4><div className="review-check-grid">{[["validEntryTrigger","Valid Entry Trigger?",false],["stopFollowed","Stop Followed?",false],["riskFollowed","Risk / Size Followed?",false],["managementFollowed","Management Followed?",true],["exitPlanFollowed","Exit According to Plan?",true]].map(([key,label,na])=><Segments key={key} label={label} value={draft[key]} options={[["yes","Yes"],["no","No"],...(na?[["na","N/A"]]:[])]} onChange={v=>update(key,v)}/>)}</div></section>
<fieldset className="rule-violation-fieldset"><legend>Rule Violations *</legend><div className="quick-violation-grid">{VIOLATIONS.map(v=><label key={v}><input type="checkbox" checked={draft.ruleViolations.includes(v)} onChange={()=>toggle(v)}/>{v}</label>)}</div></fieldset>
<section className="auto-grade"><h4>Automatic Grade</h4><div><p><span>Setup</span><strong>{grade.setupGrade}</strong></p><p><span>Execution</span><strong>{grade.executionGrade}</strong></p><p><span>Final</span><strong>{grade.finalGrade}</strong></p><p><span>Outcome</span><strong>{grade.outcomeClassification}</strong></p></div><p>{grade.explanation}</p><small>Grading version: {grade.gradingVersion}. P&amp;L never changes the grade.</small></section><label>Review Note <small>(optional)</small><textarea value={draft.reviewNote} onChange={e=>update("reviewNote",e.target.value)} placeholder="What is worth remembering from this trade?"/></label>{message?<p className={`status-message ${message.startsWith("Review saved")?"success":"error"}`}>{message}</p>:null}<div className="quick-review-actions"><Button variant="secondary" onClick={onDetailedReview}>Detailed Review</Button><Button disabled={isSaving} type="submit">{isSaving?"Saving…":"Save Review"}</Button>{onSaveNext?<Button disabled={isSaving} onClick={()=>save(true)}>Save &amp; Next</Button>:null}</div></form>}
