import { assertEquals, assertThrows } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { buildRegularSessionUrl, deriveWeeklyBias, preprocessSymbol, validateDraft, validateRequest } from "./planUtils.ts";
Deno.test("normalizes, deduplicates, and automatically includes indexes", () => assertEquals(validateRequest({ tradeDate: "2026-08-17", tickers: ["nvda", "NVDA"] }).symbols, ["QQQ", "SPY", "NVDA"]));
Deno.test("rejects invalid and oversized ticker lists", () => { assertThrows(() => validateRequest({ tradeDate: "2026-08-17", tickers: ["BAD$"] })); assertThrows(() => validateRequest({ tradeDate: "2026-08-17", tickers: Array.from({ length: 11 }, (_, index) => `T${index}`) })); });
Deno.test("calculates prior-session levels without premarket data", () => { const bar = (timestamp: string, high: number, low: number) => ({ timestamp, open: low, high, low, close: high, volume: 1 }); const daily = Array.from({ length: 30 }, (_, index) => bar(`2026-07-${String(index + 1).padStart(2, "0")}`, 10 + index, 8 + index)); const result = preprocessSymbol("QQQ", "2026-08-17", [], daily, [], []); assertEquals([result.previousDayHigh, result.previousDayLow, result.dataAvailability, result.premarketDataIncluded], [39, 37, "Full", false]); });
Deno.test("daily-only data remains a valid partial snapshot", () => { const bar = { timestamp: "2026-08-14", open: 8, high: 10, low: 7, close: 9, volume: 1 }; const result = preprocessSymbol("QQQ", "2026-08-17", [], [bar], [], []); assertEquals([result.dataAvailable, result.dataAvailability], [true, "Partial"]); });
Deno.test("Twelve Data URL has no extended-hours dependency", () => assertEquals(buildRegularSessionUrl("QQQ", "1day", 20, "secret").searchParams.has("prepost"), false));
Deno.test("derives structural weekly bias and reports insufficient history", () => { const bars = Array.from({ length: 30 }, (_, index) => ({ timestamp: new Date(Date.UTC(2026, 5, index + 1)).toISOString(), open: 100 + index, high: 102 + index, low: 99 + index, close: 101 + index, volume: 1 })); assertEquals(deriveWeeklyBias(bars), "Bullish"); assertEquals(deriveWeeklyBias(bars.slice(0, 10)), "Unavailable"); });
Deno.test("rejects fabricated premarket claims", () => assertThrows(() => validateDraft({ overall: {}, indexes: [{ ticker: "QQQ" }, { ticker: "SPY" }], watchlist: [{ ticker: "NVDA", bottomLine: "Premarket is strong" }] }, ["NVDA"])));
