import { useId, useState } from "react";
import Button from "../../components/ui/Button";

export function WatchlistPlanCard({ item, onPreview }) {
  const scenario = (side) => item[`${side}_scenario_enabled`] ? <div className={`watchlist-scenario-summary ${side}`}><strong>{side.toUpperCase()} Setup</strong><span><b>Trigger</b>{item[`${side}_trigger`] || "—"}</span><span><b>Plan</b>{item[`${side}_setup`] || "—"}</span><span><b>Invalidation</b>{item[`${side}_invalidation`] || "—"}</span></div> : <div className={`watchlist-scenario-summary ${side}`}><strong>{side.toUpperCase()} Setup</strong><span className="muted">Not planned</span></div>;
  return <div className="watchlist-execution-grid">{scenario("long")}{scenario("short")}<div className="watchlist-bottom-chart"><div className="watchlist-bottom-line-summary"><strong>Bottom Line</strong><span>{item.bottom_line || item.notes || "No game plan."}</span></div><section className="watchlist-plan-chart"><strong>Chart</strong>{item.screenshot ? <button type="button" className="watchlist-chart-thumbnail" onClick={() => onPreview?.(item)} aria-label={`Open ${item.ticker} chart`}><img src={item.screenshot} alt={`${item.ticker} pre-market chart`} /></button> : <span className="muted">No chart uploaded</span>}</section></div></div>;
}

export function WatchlistPlanTable({ items, savingId, onEdit, onDelete, onPreview }) {
  const [expandedIds, setExpandedIds] = useState(() => new Set());
  const prefix = useId().replaceAll(":", "");
  const toggle = (key) => setExpandedIds((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });
  return <div className="watchlist-plan-blocks">{items.map((item) => { const key = item.id || item.ticker; const expanded = expandedIds.has(key); const detailId = `${prefix}-${key}-trade-plan`; const deleting = savingId != null && savingId === item.id; return <article className="watchlist-plan-block" key={key}><header className="watchlist-plan-header"><div className="watchlist-plan-metadata"><h3>{item.ticker}</h3><span>Weekly: <em className="plan-bias-badge">{item.weekly_bias || "Unknown"}</em></span><span>Daily: <em className="plan-bias-badge">{item.daily_bias || "Unknown"}</em></span><span>RS/RW: <b>{item.relative_strength || "—"}</b></span><span>Preferred: <em className="plan-direction-badge">{item.direction || "Neutral"}</em></span><span>Confidence: <b>{item.confidence || "—"}</b></span><span className="major-level-badge">Major Support: <b>{item.major_support ?? "—"}</b></span><span className="major-level-badge">Major Resistance: <b>{item.major_resistance ?? "—"}</b></span></div><div className="plan-table-actions"><Button variant="secondary" aria-expanded={expanded} aria-controls={detailId} onClick={() => toggle(key)}>{expanded ? "Hide Trade Plan" : "Show Trade Plan"}</Button><Button variant="secondary" onClick={(event) => onEdit(event, item)}>Edit</Button><Button variant="danger" disabled={deleting} onClick={(event) => onDelete(event, item.id)}>{deleting ? "Deleting..." : "Delete"}</Button></div></header>{expanded ? <div id={detailId}><WatchlistPlanCard item={item} onPreview={onPreview} /></div> : null}</article>; })}</div>;
}
